_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 07bd2dc3-59b1-44a6-bc2b-5ebcd613c76d
name: erson-d9-build-tools
mail: erson.nogot@getpantheon.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
