name: Deploy to Dev

on:
  push:
    branches:
      - main  

env:
  TERMINUS_SITE: erson-d9-build-tools
  TERMINUS_ENV: dev
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Terminus
      run: |
        mkdir -p ~/terminus && cd ~/terminus
        curl -L https://github.com/pantheon-systems/terminus/releases/download/3.1.0/terminus.phar --output terminus
        chmod +x terminus
        sudo ln -s ~/terminus/terminus /usr/local/bin/terminus
        terminus -V
        
    - name: Install Build Tools
      run: terminus self:plugin:install terminus-build-tools-plugin

    - name: Login with Terminus
      run: terminus -n auth:login --machine-token=${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Prepare code for deployment
      run: |
        git config --global user.email "erson.nogot@getpantheon.com "
        git config --global user.name "GitHub Actions"
   
    - name: Login with Terminus
      run: terminus self:plugin:list
      
   # Deploy to Pantheon
    - name: Place SSH key
      # uses: shimataro/ssh-key-action@6f350ca8484d8d55c2e361e74d17e638dabe713a # v2.1.0
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Terminus - Push
      run: terminus -n build:env:push "$TERMINUS_SITE.dev" --yes -vvv
  
    # - name: Terminus - Import
    #   run: |
    #     if [ -f "config/system.site.yml" ] ; then
    #     terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes
    #     fi